

import { 
  Desarrollo, Nivel, Modelo, ModeloAgrupador, 
  Estado, EstadoAgrupador, DTUAvaluo, MetodoCompra, MetodoCompraAgrupador,
  Banco, TipoUsuario, Asesor
} from './types';

export const CATALOGOS = {
  desarrollo: Object.values(Desarrollo),
  nivel: Object.values(Nivel),
  modelo: Object.values(Modelo),
  modeloAgrupador: Object.values(ModeloAgrupador),
  estado: Object.values(Estado),
  estadoAgrupador: Object.values(EstadoAgrupador),
  dtuAvaluo: Object.values(DTUAvaluo),
  metodoCompra: Object.values(MetodoCompra),
  metodoCompraAgrupador: Object.values(MetodoCompraAgrupador),
  banco: Object.values(Banco),
  tipoUsuario: Object.values(TipoUsuario),
  asesor: Object.values(Asesor),
};

export const SCHEMA_DEFINITION = [
  { field: 'idPropiedad', type: 'Alfanumérico', obs: 'Registro único, Se genera automático.', values: 'pnty-000001 (Consecutivo)' },
  { field: 'Desarrollo', type: 'Alfanumérico (ENUM)', obs: 'Campo ENUM', values: Object.values(Desarrollo).join(', ') },
  { field: 'Nivel', type: 'Alfanumérico (ENUM)', obs: 'Campo ENUM', values: Object.values(Nivel).join(', ') },
  { field: 'Modelo', type: 'Alfanumérico (ENUM)', obs: 'Campo ENUM', values: Object.values(Modelo).join(', ') },
  { field: 'Modelo Agrupador', type: 'Alfanumérico (ENUM)', obs: 'Campo ENUM', values: Object.values(ModeloAgrupador).join(', ') },
  { field: 'Estado', type: 'Alfanumérico (ENUM)', obs: 'Campo ENUM', values: Object.values(Estado).join(', ') },
  { field: 'Estado Agrupador', type: 'Alfabético', obs: 'Campo ENUM', values: Object.values(EstadoAgrupador).join(', ') },
  { field: 'Precio de lista', type: 'Currency', obs: 'Enteros', values: '-' },
  { field: 'Descuento', type: 'Currency', obs: 'Enteros, negativo', values: '-' },
  { field: 'Precio Final', type: 'Currency', obs: 'Enteros', values: '-' },
  { field: 'Precio Operación', type: 'Currency', obs: 'Enteros', values: '-' },
  { field: 'M2 Terr Exc', type: 'Numérico', obs: '1 decimal', values: '-' },
  { field: '$ x m2 Exc', type: 'Currency', obs: 'Enteros', values: '-' },
  { field: '$ Terr Exc', type: 'Currency', obs: 'Enteros', values: '-' },
  { field: '$ Obras adicionales', type: 'Currency', obs: 'Enteros', values: '-' },
  { field: 'Obras Adicionales', type: 'Texto', obs: '', values: '-' },
  { field: 'EK', type: 'Texto', obs: 'ID del ERP', values: '-' },
  { field: 'Nombre Comprador', type: 'Alfabético', obs: 'MAYÚSCULAS', values: '-' },
  { field: 'DTU-Avalúo', type: 'ENUM', obs: 'Campo ENUM', values: Object.values(DTUAvaluo).join(', ') },
  { field: 'Valor Avalúo', type: 'Currency', obs: 'Enteros', values: '-' },
  { field: 'Días autorizados Apartado', type: 'Numérico', obs: 'Base para cálculo de rezago', values: '-' },
  { field: 'Días de atraso de apartado', type: 'Calculado', obs: '', values: '-' },
  { field: 'Días Rezago Apartado', type: 'Calculado', obs: 'Calculado vs Días Autorizados', values: '-' },
  { field: 'Método Compra', type: 'Alfanumérico (ENUM)', obs: 'Campo ENUM', values: Object.values(MetodoCompra).join(', ') },
  { field: 'Método Compra Agrupador', type: 'Alfanumérico (ENUM)', obs: 'Campo ENUM (Calculado)', values: Object.values(MetodoCompraAgrupador).join(', ') },
  { field: 'Banco', type: 'Alfanumérico (ENUM)', obs: 'Campo ENUM', values: Object.values(Banco).join(', ') },
  { field: 'Asesor Externo', type: 'TRUE/FALSE', obs: '', values: '-' },
  { field: 'Asesor', type: 'Alfanumérico (ENUM)', obs: 'Campo ENUM', values: Object.values(Asesor).join(', ') },
  { field: 'Observaciones', type: 'Texto', obs: 'Notas libres', values: '-' },
  { field: 'Calle', type: 'Alfanumérico', obs: '', values: '-' },
  { field: 'Manzana', type: 'Alfanumérico', obs: '', values: '-' },
  { field: 'Lote', type: 'Alfanumérico', obs: '', values: '-' },
  { field: 'Edificio', type: 'Alfanumérico', obs: '', values: '-' },
  { field: 'Número Exterior', type: 'Alfanumérico', obs: '', values: '-' },
  { field: 'Número Interior', type: 'Alfanumérico', obs: '', values: '-' },
  { field: 'Condomino', type: 'Alfanumérico', obs: '', values: '-' },
  { field: 'Tipo usuario', type: 'Alfanumérico (ENUM)', obs: 'Campo ENUM', values: Object.values(TipoUsuario).join(', ') },
  { field: 'Documentos', type: 'imagen/documento', obs: 'Archivos adjuntos', values: '-' },
  { field: 'Fechas', type: 'Fecha', obs: 'Apartado, Venta, Escritura', values: '-' },
];